### ISSUE TITLE
Add a subscription?

### ISSUE THREAD

**Issue by ebraminio** [Athou/commafeed-newsplus#6]
Hi! Is add a subscription is broken with recent News+? This is what I see on logcat:

``` logcat
W/System.err(21436): java.lang.NullPointerException
W/System.err(21436):    at com.commafeed.newsplus.APIHelper.convertID(APIHelper.java:22)
W/System.err(21436):    at com.commafeed.newsplus.CommaFeedExtension.editSubscription(CommaFeedExtension.java:320)
W/System.err(21436):    at com.noinnion.android.reader.api.ReaderExtension$1.editSubscription(ReaderExtension.java:224)
W/System.err(21436):    at com.noinnion.android.reader.api.internal.IReaderExtension$Stub.onTransact(IReaderExtension.java:152)
W/System.err(21436):    at android.os.Binder.execTransact(Binder.java:404)
W/System.err(21436):    at dalvik.system.NativeStart.run(Native Method)
W/System.err(21465): com.noinnion.android.reader.api.ReaderException: ERROR_UNKNOWN: null
W/System.err(21465):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.checkError(ReaderManager.java:1103)
W/System.err(21465):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.subscribeFeed(ReaderManager.java:3198)
W/System.err(21465):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.subscribeFeedEx(ReaderManager.java:3180)
W/System.err(21465):    at com.noinnion.android.newsplus.reader.ui.fragment.SubscribeSearchFragment$SubscribeTask.doInBackground(SubscribeSearchFragment.java:349)
W/System.err(21465):    at com.noinnion.android.newsplus.reader.ui.fragment.SubscribeSearchFragment$SubscribeTask.doInBackground(SubscribeSearchFragment.java:1)
```

I will also look at a fix by my self of-course :)

**Comment by Athou** [comment]
Can you try now please?

**Comment by ebraminio** [comment]
503 service unavailable :(

```
W/RestTemplate( 3736): POST request for "https://www.commafeed.com/rest/feed/subscribe" resulted in 503 (Service Unavailable); invoking error handler
W/System.err( 3736): org.springframework.web.client.HttpServerErrorException: 503 Service Unavailable
W/System.err( 3736):    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:78)
W/System.err( 3736):    at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:524)
W/System.err( 3736):    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:481)
W/System.err( 3736):    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:439)
W/System.err( 3736):    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:415)
W/System.err( 3736):    at com.commafeed.newsplus.CommaFeedClient_.feedSubscribe(CommaFeedClient_.java:194)
W/System.err( 3736):    at com.commafeed.newsplus.CommaFeedExtension.editSubscription(CommaFeedExtension.java:332)
W/System.err( 3736):    at com.noinnion.android.reader.api.ReaderExtension$1.editSubscription(ReaderExtension.java:224)
W/System.err( 3736):    at com.noinnion.android.reader.api.internal.IReaderExten
sion$Stub.onTransact(IReaderExtension.java:152)
W/System.err( 3736):    at android.os.Binder.execTransact(Binder.java:404)
W/System.err( 3736):    at dalvik.system.NativeStart.run(Native Method)
W/System.err( 3710): com.noinnion.android.reader.api.ReaderException: ERROR_UNKNOWN: 503 Service Unavailable
W/System.err( 3710):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.checkError(ReaderManager.java:1103)
W/System.err( 3710):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.subscribeFeed(ReaderManager.java:3198)
W/System.err( 3710):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.subscribeFeedEx(ReaderManager.java:3180)
```

**Comment by Athou** [comment]
Okay https://github.com/Athou/commafeed/commit/a861387bd74f58e6825153fa6dcef281f166e5bb should fix it.

**Comment by ebraminio** [comment]
Thank you very much
